name: Create Package Version For CI

on:
  push:
    branches: [core, app1, app2]  

jobs:
  getBranchName:
      - name: Get branch name
      id: branch-name
      uses: tj-actions/branch-names@v5.2
  createVersion:
      uses: ./.github/workflows/CreatePackageVersion.yml
      with:
        runApexTest: 'true'
        skipValidation: 'false'
        packageName: ${{ jobs.getBranchName.steps.branch-name.outputs.current_branch }} 
        waitTime: 1000
      secrets:
        DEVHUB_clientid: ${{ secrets.DEVHUB_clientid }}
        RSA_PRIVATE_KEY: ${{ secrets.RSA_PRIVATE_KEY }}
        PACKAGES_KEY: ${{ secrets.PACKAGES_KEY }}
