name: Create Package Version For CI

on:
  push:
    branches: [core, App1, App2]  

jobs:
  getBranchName:
    runs-on: ubuntu-latest
    steps:
      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v5.2
    outputs: 
      branchName: ${{ steps.branch-name.outputs.current_branch }} 
  createVersion:
      needs: getBranchName
      uses: ./.github/workflows/CreatePackageVersion.yml
      with:
        runApexTest: 'true'
        skipValidation: 'false'
        packageName: ${{ needs.getBranchName.outputs.branchName }}
        waitTime: 1000
      secrets:
        DEVHUB_clientid: ${{ secrets.DEVHUB_clientid }}
        RSA_PRIVATE_KEY: ${{ secrets.RSA_PRIVATE_KEY }}
        PACKAGES_KEY: ${{ secrets.PACKAGES_KEY }}
